backend:
  name: github
  repo: "kaleyvuong/pie-web" # Replace with your GitHub username and repository name

media_folder: "src/assets" # The folder where uploaded media files are stored
public_folder: "/assets" # The URL path to access the uploaded media files
site_url: "https://pie-web.netlify.app/

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }